Repository Shalevro2/UniGrade, pull requests merged in 2023-08, with the labels that each got.

#64 Color input changes
  public/add_course.html
  public/css/add_course.css
Labels: bug

#72 change placeholder
  public/add_course.html
Labels: bug

#77 Update README.md
  README.md
Labels: documentation

#76 navbar updates
  public/add_course.html
  public/courses_overview.html
Labels: enhancement

#73 fix logout button
  public/add_course.html
  public/courses_overview.html
  public/js/add_course.js
  public/js/courses_overview.js
Labels: bug

#80 fixing the issue with the conflict
  public/courses_overview.html
Labels: bug

#78 fixing total precent and grade validate
  public/add_course.html
  public/js/add_course.js
Labels: bug

#81 adding courses table to overview
  public/courses_overview.html
  public/css/courses_overview.css
  public/index.html
  public/js/courses_overview.js
Labels: enhancement
