Repository Shalevro2/UniGrade, pull requests merged in 2023-06, with the labels that each got.

#28 Adding uml
  UML/Class diagram.png
  UML/add course activity.png
  UML/overall activity.png
  UML/state machine activity.png
  UML/uml
  UML/uml.drawio.pdf
  UML/use case.png
Labels: documentation

#32 Adding landing page and sign up page
  public/css/common.css
  public/css/index.css
  public/css/sign_up.css
  public/index.html
  public/js/sign_up.js
  public/pictures/UniGrade.png
  public/pictures/big_logo.png
  public/pictures/index_back.jpeg
  public/pictures/unigrade_logo.png
  public/sign_up.html
Labels: enhancement

#33 Update README.md
  README.md
Labels: documentation

#35 connect firebase and setup the signup
  public/js/sign_up.js
  public/sign_up.html
Labels: enhancement

#37 Add signin function
  public/js/sign_up.js
  public/sign_up.html
Labels: enhancement

#39 union buttons
  public/index.html
Labels: enhancement

#41 Adding add-course page
  public/add_course.html
  public/css/add_course.css
Labels: enhancement

#43 Change some css
  public/css/add_course.css
Labels: enhancement

#46 Add add_course.js and connect
  public/add_course.html
  public/js/Course.js
  public/js/add_course.js
  public/js/sign_up.js
Labels: enhancement

#49 Fix the issues with the add course page
  public/add_course.html
  public/css/add_course.css
  public/js/add_course.js
  public/sign_up.html
Labels: bug

#50 fixing the issue with the add-course require
  public/add_course.html
  public/js/add_course.js
  public/js/sign_up.js
Labels: bug

#52 Add error box for login and sign up
  public/js/sign_up.js
  public/sign_up.html
Labels: bug, enhancement

#57 Navbar
  public/add_course.html
  public/css/navbar.css
  public/js/navbar.js
Labels: enhancement

#58 Add delete and add buttons with functionality
  public/add_course.html
  public/css/add_course.css
  public/js/add_course.js
Labels: enhancement

#62 css updates
  public/add_course.html
  public/css/add_course.css
  public/js/add_course.js
Labels: enhancement

#61 open overview from dashboard
  public/add_course.html
  public/js/navbar.js
Labels: enhancement

#63 Adding alert msg at add course page
  public/add_course.html
  public/css/add_course.css
  public/js/add_course.js
Labels: enhancement
